kind = "web"
previewPath = "/"
title = "Newcastle.dog"

[[services]]
localPort = 3000
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/newcastle-dog run dev"

[services.development.env]
PORT = "3000"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/newcastle-dog", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["pnpm", "--filter", "@workspace/newcastle-dog", "run", "start"]

[services.production.run.env]
PORT = "3000"
NODE_ENV = "production"
